version: '3'
services:
    webapp:
        build:
            context: .
            dockerfile: ./docker/7.4-fpm-alpine/Dockerfile
        image: fpm-alpine-7.4/uq-jix
        ports:
            - '32100:80'
